### ISSUE TITLE
Assembly-Picture1

### ISSUE THREAD

**Issue by the-mentalaist** [fmalpartida/SAV-MAKER-I#1]
![imagen1](https://cloud.githubusercontent.com/assets/15377447/10862928/b0128094-7fbc-11e5-912e-b9c856a20be8.JPG)

**Comment by areyesl** [comment]
Hola, 
Imagino que abriste este issue porque querías incrustar esta imagen en la wiki. Si era eso, ten en cuenta que para incrustar imagenes es necesario que éstas estén en un repositorio Github.
Saludos,
Arcadio

**Comment by fmalpartida** [comment]
Exacto. Deje un directorio imagen para ir subiendo todas las imágenes y enlazarlas en la wiki.

**Comment by the-mentalaist** [comment]
Pues sí, era por eso. El problema es que no sé cómo subir las imágenes al repositorio.

**Comment by fmalpartida** [comment]
Looking nice the assembly manual.
